site_name: DarkMAGIC
#site_url: 'https://oashour.github.io/DarkMAGIC/'

nav:
  - Home: index.md
  - Formalism: formalism.md
theme: 
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - search.highlight
    - search.share

extra:
  version:
    provider: mike

plugins:
  - search
  - mike
